#!/bin/bash
#  Create & manage middleware
#  shellcheck disable=SC2155

set -o nounset
set -o errexit


function usage() {
    echo -e "\033[33mUsage:\033[0m ezctl COMMAND [args]"
    cat <<EOF
-------------------------------------------------------------------------------------
Middleware setups:
    list		             to list all of the managed clusters
    checkout    <cluster>            to switch default kubeconfig of the cluster
    new         <cluster>            to start a new k8s deploy with name 'cluster'
    setup       <cluster>  <step>    to setup a cluster, also supporting a step-by-step way
    start       <cluster>            to start all of the k8s services stopped by 'ezctl stop'
    stop        <cluster>            to stop all of the k8s services temporarily
    upgrade     <cluster>            to upgrade the k8s cluster
    destroy     <cluster>            to destroy the k8s cluster
    backup      <cluster>            to backup the cluster state (etcd snapshot)
    restore     <cluster>            to restore the cluster state from backups
    start-aio		             to quickly setup an all-in-one cluster with default settings

Use "ezctl help <command>" for more information about a given command.
EOF
}

function logger() {
    TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
    local FNAME=$(basename "${BASH_SOURCE[1]}")
    local SOURCE="\033[36m[$FNAME:${BASH_LINENO[0]}]\033[0m"
    case "$1" in
        debug)
            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[36mDEBUG $2\033[0m"
            ;;
        info)
            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[32mINFO $2\033[0m"
            ;;
        warn)
            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[33mWARN $2\033[0m"
            ;;
        error)
            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[31mERROR $2\033[0m"
            ;;
        *) ;;
    esac
}


function usage-setup(){
  echo -e "\033[33mUsage:\033[0m ezctl setup <cluster> <step>"
  cat <<EOF
available steps:
    01  prepare            to prepare system settings
    02  container-runtime  to setup the container runtime(docker or containerd)

examples: ./ezctl setup 01  (or ./ezctl setup prepare)
	      ./ezctl setup 02  (or ./ezctl setup container-runtime)
EOF
}

### Middleware setups functions ##############################

function new() {
    # check if already existed
    [[ -d "middleware" ]] && { logger error "middleware already existed, if middleware setup failed, try 'rm -rf $BASE/middleware' first!"; exit 1; }

    logger debug "generate custom middleware files in $BASE/middleware"
    mkdir -p "middleware"
    cp example/hosts.multi-node "middleware/hosts"
    # sed -i "s/_cluster_name_/$1/g" "clusters/$1/hosts"
    cp example/config.yml "middleware/config.yml"

    logger debug "set versions"
    # these variables were imported with eval and have the same name in ezdown
    eval $(sed '/V.[rR]=.*\./!d' ezdown)
    # k8sVer=$(echo "$K8S_BIN_VER"|sed 's/v//g')
    # registryMirror=true

    # grep registry-mirrors /etc/docker/daemon.json > /dev/null 2>&1 || { logger debug "disable registry mirrors"; registryMirror=false; }

    sed -i -e "s/__redis__/$redisVer/g" \
       -e "s/__mysql__/$mysqlVer/g" \
	   -e "s/__kafka__/$kafkaVer/g" \
	   -e "s/__rocketmq__/$rocketmqVer/g" \
	   -e "s/__rabbitmq__/$rabbitmqVer/g" \
	   -e "s/__zookeeper__/$zookeeperVer/g" \
	   -e "s/__nginx__/$nginxVer/g" \
	   -e "s/__tomcat__/$tomcatVer/g" \
	   -e "s/__elasticsearch__/$elasticsearchVer/g" "middleware/config.yml"


    logger debug "middleware: files successfully created."
    logger info "next steps 1: to config '$BASE/middleware/hosts'"
    logger info "next steps 2: to config '$BASE/middleware/config.yml'"
}

function setup() {
    [[ -d "middleware" ]] || { logger error "invalid config, run 'ezctl new' first"; return 1; }

    # for extending usage
    EXTRA_ARGS=$(echo "$*"|sed "s/$1 $2//g"|sed "s/^ *//g")

    PLAY_BOOK="dummy.yml"
    case "$2" in
      (01|prepare)
          PLAY_BOOK="01.prepare.yml"
          ;;
      (02|container-runtime)
          PLAY_BOOK="02.runtime.yml"
          ;;
      (*)
          usage-setup
          exit 1
          ;;
    esac

    COMMAND="ansible-playbook -i middleware/hosts -e @middleware/config.yml $EXTRA_ARGS playbooks/$PLAY_BOOK"
    echo "$COMMAND"

    logger info "cluster:$1 setup step:$2 begins in 5s, press any key to abort:\n"
    ! (read -r -t5 -n1) || { logger warn "setup abort"; return 1; }

    ${COMMAND} || return 1
}

function cmd() {
    [[ -d "middleware" ]] || { logger error "invalid config, run 'ezctl new' first"; return 1; }

    PLAY_BOOK="dummy.yml"
    case "$1" in
      (start)
          PLAY_BOOK="91.start.yml"
          ;;
      (stop)
          PLAY_BOOK="92.stop.yml"
          ;;
      (upgrade)
          PLAY_BOOK="93.upgrade.yml"
          ;;
      (backup)
          PLAY_BOOK="94.backup.yml"
          ;;
      (restore)
          PLAY_BOOK="95.restore.yml"
          ;;
      (destroy)
          PLAY_BOOK="99.clean.yml"
          ;;
      (*)
          usage
          exit 1
          ;;
    esac

    COMMAND="ansible-playbook -i clusters/$1/hosts -e @clusters/$1/config.yml playbooks/$PLAY_BOOK"
    echo "$COMMAND"

    logger info "cluster:$1 $2 begins in 5s, press any key to abort:\n"
    ! (read -r -t5 -n1) || { logger warn "$2 abort"; return 1; }

    ${COMMAND} || return 1
}

### Main Lines ##################################################
function main() {
  BASE="/etc/kubemid"
  [[ -d "$BASE" ]] || { logger error "invalid dir:$BASE, try: 'ezdown -D'"; exit 1; }
  cd "$BASE"

  # check bash shell
  readlink /proc/$$/exe|grep -q "bash" || { logger error "you should use bash shell only"; exit 1; }

  # check 'ansible' executable
  which ansible > /dev/null 2>&1 || { logger error "need 'ansible', try: 'pip install ansible'"; usage; exit 1; }

  [ "$#" -gt 0 ] || { usage >&2; exit 2; }

  case "$1" in
      (new)
          [ "$#" -eq 1 ] || { usage >&2; exit 2; }
          new
          ;;
      (setup)
          [ "$#" -ge 3 ] || { usage-setup >&2; exit 2; }
          setup "${@:2}"
          ;;
      (start)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          cmd "$2" start
          ;;
      (stop)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          cmd "$2" stop
          ;;
      (upgrade)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          cmd "$2" upgrade
          ;;
      (backup)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          cmd "$2" backup
          ;;
      (restore)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          cmd "$2" restore
          ;;
      (destroy)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          cmd "$2" destroy
          ;;
      (*)
          usage
          exit 0
          ;;
  esac
 }

main "$@"
