# [optional] to synchronize system time of nodes with 'chrony' 
- hosts:
  - docker
  - nginx
  - chrony
  roles:
  - { role: os-harden, when: "OS_HARDEN|bool" }
  - { role: chrony, when: "groups['chrony']|length > 0" }

# prepare tasks for all nodes
- hosts:
  - docker
  - nginx
  roles:
  - prepare
